### ISSUE TITLE
Rename the config directory to setup

### ISSUE THREAD

**Issue by sebastianks** [sebastianks/volcano#22]
The `config` directory is more of a Setup kind of thing, which is why I think it should be renamed to `setup`.

**Comment by zliel** [comment]
Hi @sebastianks, can I work on this?

**Comment by sebastianks** [comment]
Hi @zliel, sure thing!

**Comment by sebastianks** [comment]
@zliel I moved the issue to "In Progress" and assigned it to you. Let me know, if you need help of any kind 😉

**Comment by zliel** [comment]
@sebastianks Sounds good, thank you! Just to make sure, you just want the `config` directory renamed to `setup`?

**Comment by sebastianks** [comment]
@zliel That is correct, yes. There is also a couple of mentions of the directory in the README, which needs to be updated.

**Comment by zliel** [comment]
Just finished up, if anything's wrong with my PR please let me know!

**Comment by sebastianks** [comment]
@zliel Congrats on your first contribution to Volcano! And many thanks for taking your time to do this!
